/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    ActionDesigner: typeof import('./../components/molian/components/designer/actionDesigner/index.vue')['default']
    AnimateHeight: typeof import('./../components/molian/components/animate-height/index.vue')['default']
    AnyData2form: typeof import('./../components/molian/components/any-data2form/index.vue')['default']
    Basic: typeof import('./../components/molian/components/designer/optionsDesigner/components/basic.vue')['default']
    CategoryPanel: typeof import('./../components/molian/components/designer/compsDesigner/category-panel.vue')['default']
    CodeEditor: typeof import('./../components/molian/components/code-editor/index.vue')['default']
    CodeInput: typeof import('./../components/molian/components/code-input/index.vue')['default']
    ColorPicker: typeof import('./../components/molian/components/color-picker/index.vue')['default']
    CompsDesigner: typeof import('./../components/molian/components/designer/compsDesigner/index.vue')['default']
    ContainerDesigner: typeof import('./../components/molian/components/designer/containerDesigner/index.vue')['default']
    Create: typeof import('./../components/molian/components/designer/globalDesigner/global-panel/create.vue')['default']
    CssDesigner: typeof import('./../components/molian/components/designer/cssDesigner/index.vue')['default']
    Data2input: typeof import('./../components/molian/components/data2input/index.vue')['default']
    DeepTreeToData: typeof import('./../components/molian/components/designer/containerDesigner/treeDir/deepTreeToData.vue')['default']
    DeepTreeToDesigner: typeof import('./../components/molian/components/designer/containerDesigner/deepTreeToDesigner.vue')['default']
    DeepTreeToRender: typeof import('./../components/molian/components/render/deepTreeToRender.vue')['default']
    Designer: typeof import('./../components/molian/components/designer/index.vue')['default']
    Effect: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/effect.vue')['default']
    Fill: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/fill.vue')['default']
    FloatBall: typeof import('./../components/molian/components/float-ball/index.vue')['default']
    FloatPanel: typeof import('./../components/molian/components/float-panel/index.vue')['default']
    Font: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/font.vue')['default']
    For: typeof import('./../components/molian/components/designer/optionsDesigner/tooltip/for.vue')['default']
    GlobalDesigner: typeof import('./../components/molian/components/designer/globalDesigner/index.vue')['default']
    GlobalTool: typeof import('./../components/molian/components/designer/globalTool/index.vue')['default']
    If: typeof import('./../components/molian/components/designer/optionsDesigner/tooltip/if.vue')['default']
    Javascript: typeof import('./../components/molian/components/designer/optionsDesigner/components/javascript.vue')['default']
    Lifecycle: typeof import('./../components/molian/components/designer/optionsDesigner/components/lifecycle.vue')['default']
    Margin: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/margin.vue')['default']
    NativeOn: typeof import('./../components/molian/components/designer/optionsDesigner/components/nativeOn.vue')['default']
    OptionsDesigner: typeof import('./../components/molian/components/designer/optionsDesigner/index.vue')['default']
    Render: typeof import('./../components/molian/components/render/index.vue')['default']
    Show: typeof import('./../components/molian/components/designer/optionsDesigner/tooltip/show.vue')['default']
    Slot: typeof import('./../components/molian/components/designer/optionsDesigner/components/slot.vue')['default']
    SlotTemplate: typeof import('./../components/molian/components/render/slotTemplate.vue')['default']
    StickyTool: typeof import('./../components/molian/components/sticky-tool/index.vue')['default']
    Stroke: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/stroke.vue')['default']
    SubForm: typeof import('./../components/molian/components/sub-form/index.vue')['default']
    SvgIcon: typeof import('./../components/molian/components/svg-icon/index.vue')['default']
    TagInput: typeof import('./../components/molian/components/tag-input/index.vue')['default']
    ToolTip: typeof import('./../components/molian/components/designer/containerDesigner/toolTip/index.vue')['default']
    Transform: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/transform.vue')['default']
    TransformBottom: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/transform/transform-bottom.vue')['default']
    TransformTop: typeof import('./../components/molian/components/designer/cssDesigner/css-tool-panel/transform/transform-top.vue')['default']
    TreeDir: typeof import('./../components/molian/components/designer/containerDesigner/treeDir/index.vue')['default']
    Variable: typeof import('./../components/molian/components/designer/optionsDesigner/tooltip/variable.vue')['default']
  }
}
